# Generated by Django 6.0.4 on 2026-04-14 02:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tiempo_adicional_dias', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Acople',
                'verbose_name_plural': 'Acoples',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SUCCION', 'Succión'), ('DESCARGA', 'Descarga')], max_length=20)),
                ('diametro', models.CharField(max_length=20)),
                ('ansi', models.CharField(max_length=20)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tiempo_adicional_dias', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conexión',
                'verbose_name_plural': 'Conexiones',
                'ordering': ['tipo', 'diametro', 'ansi'],
            },
        ),
        migrations.CreateModel(
            name='EquipoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipo', models.CharField(max_length=20, unique=True)),
                ('nombre_equipo', models.CharField(max_length=150)),
                ('bomba', models.CharField(max_length=150)),
                ('camara_empuje', models.CharField(blank=True, default='', max_length=100)),
                ('carga_camara_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('potencia_hp_min', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('potencia_hp_max', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('caudal_min_bpd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('caudal_max_bpd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ps_min_psi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ps_max_psi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pd_min_psi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pd_max_psi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tiempo_base_dias', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Equipo base',
                'verbose_name_plural': 'Equipos base',
                'ordering': ['id_equipo'],
            },
        ),
        migrations.CreateModel(
            name='MarcaMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca de motor',
                'verbose_name_plural': 'Marcas de motor',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Variador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('potencia_hp_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('potencia_hp_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tiempo_adicional_dias', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Variador',
                'verbose_name_plural': 'Variadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CurvaOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_punto', models.CharField(max_length=20, unique=True)),
                ('caudal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dp_requerida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('potencia_hp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carga_camara', models.DecimalField(decimal_places=2, max_digits=12)),
                ('eficiencia_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_punto', models.CharField(choices=[('NOMINAL', 'Nominal'), ('BAJA_EFICIENCIA', 'Baja eficiencia'), ('ALTO_CAUDAL', 'Alto caudal')], default='NOMINAL', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curvas', to='cotizador.equipobase')),
            ],
            options={
                'verbose_name': 'Curva de operación',
                'verbose_name_plural': 'Curvas de operación',
                'ordering': ['equipo__id_equipo', 'caudal'],
            },
        ),
        migrations.CreateModel(
            name='OpcionMotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia_hp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voltaje', models.CharField(blank=True, default='', max_length=50)),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tiempo_adicional_dias', models.PositiveIntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_motor', to='cotizador.equipobase')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cotizador.marcamotor')),
            ],
            options={
                'verbose_name': 'Opción de motor',
                'verbose_name_plural': 'Opciones de motor',
                'ordering': ['equipo__id_equipo', 'marca__nombre', 'potencia_hp'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=150)),
                ('contacto', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('presion_succion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('presion_descarga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('caudal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dp_calculada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tiempo_entrega_estimado_dias', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acople', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.acople')),
                ('conexion_descarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_descarga', to='cotizador.conexion')),
                ('conexion_succion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_succion', to='cotizador.conexion')),
                ('equipo_recomendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='cotizador.equipobase')),
                ('motor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.opcionmotor')),
                ('punto_recomendado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='cotizador.curvaoperacion')),
                ('variador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.variador')),
            ],
            options={
                'verbose_name': 'Solicitud de cotización',
                'verbose_name_plural': 'Solicitudes de cotización',
                'ordering': ['-created_at'],
            },
        ),
    ]
