# Generated by Django 6.0.4 on 2026-04-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_equipobase_longitud_total_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipobase',
            name='curva_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='curvas_equipos/'),
        ),
    ]
