# Generated by Django 6.0.4 on 2026-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_equipobase_curva_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='nombre_proyecto',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='solicitudcotizacion',
            name='observaciones_cliente',
            field=models.TextField(blank=True, default=''),
        ),
    ]
