# Generated by Django 6.0.4 on 2026-04-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_solicitudcotizacion_nombre_proyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudReparacionCamara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=150)),
                ('contacto', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('nombre_proyecto', models.CharField(blank=True, default='', max_length=150)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_reparacion', models.CharField(choices=[('MENOR', 'Menor'), ('MAYOR', 'Mayor')], max_length=20)),
                ('observaciones_cliente', models.TextField(blank=True, default='')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tiempo_estimado_dias', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Solicitud reparación cámara',
                'verbose_name_plural': 'Solicitudes reparación cámara',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReparacionCamaraTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('tipo_reparacion', models.CharField(choices=[('MENOR', 'Menor'), ('MAYOR', 'Mayor')], max_length=20)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tiempo_estimado_dias', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tarifa reparación cámara',
                'verbose_name_plural': 'Tarifas reparación cámara',
                'ordering': ['marca', 'modelo', 'tipo_reparacion'],
                'unique_together': {('marca', 'modelo', 'tipo_reparacion')},
            },
        ),
    ]
