# Generated by Django 6.0.4 on 2026-04-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_solicitudreparacioncamara_reparacioncamaratarifa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reparacioncamaratarifa',
            name='tiempo_estimado_dias',
        ),
        migrations.RemoveField(
            model_name='solicitudreparacioncamara',
            name='tiempo_estimado_dias',
        ),
        migrations.AddField(
            model_name='reparacioncamaratarifa',
            name='observacion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reparacioncamaratarifa',
            name='tiempo_estimado_texto',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='solicitudreparacioncamara',
            name='observacion_tecnica',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='solicitudreparacioncamara',
            name='tiempo_estimado_texto',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reparacioncamaratarifa',
            name='tipo_reparacion',
            field=models.CharField(choices=[('MENOR', 'Menor'), ('MAYOR', 'Mayor'), ('UPGRADE', 'Upgrade')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudreparacioncamara',
            name='tipo_reparacion',
            field=models.CharField(choices=[('MENOR', 'Menor'), ('MAYOR', 'Mayor'), ('UPGRADE', 'Upgrade')], max_length=20),
        ),
    ]
