# Generated by Django 6.0.4 on 2026-04-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0006_remove_reparacioncamaratarifa_tiempo_estimado_dias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreparacioncamara',
            name='fecha_solicitud_precio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudreparacioncamara',
            name='solicito_precio',
            field=models.BooleanField(default=False),
        ),
    ]
