# Generated by Django 6.0.4 on 2026-04-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0007_solicitudreparacioncamara_fecha_solicitud_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoVariador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('nombre_falla', models.CharField(max_length=200)),
                ('causa_probable', models.TextField(blank=True, default='')),
                ('accion_recomendada', models.TextField(blank=True, default='')),
                ('categoria', models.CharField(blank=True, default='', max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Diagnóstico Variador',
                'verbose_name_plural': 'Diagnósticos Variadores',
                'ordering': ['marca', 'codigo'],
            },
        ),
    ]
