# Generated by Django 6.0.4 on 2026-04-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0008_diagnosticovariador'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='diagnosticovariador',
            unique_together={('marca', 'codigo')},
        ),
    ]
