# Generated by Django 6.0.4 on 2026-05-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0009_alter_diagnosticovariador_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaDiagnosticoVariadorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('codigo', models.CharField(blank=True, default='', max_length=100)),
                ('encontrado', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('session_key', models.CharField(blank=True, default='', max_length=80)),
                ('referer', models.TextField(blank=True, default='')),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('es_sospechoso', models.BooleanField(default=False)),
                ('notificacion_enviada', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log consulta VSD',
                'verbose_name_plural': 'Logs consultas VSD',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ip_address', 'created_at'], name='cotizador_c_ip_addr_c15d50_idx'), models.Index(fields=['session_key', 'created_at'], name='cotizador_c_session_91f089_idx'), models.Index(fields=['es_sospechoso', 'created_at'], name='cotizador_c_es_sosp_184da2_idx')],
            },
        ),
    ]
