# Generated by Django 6.0.4 on 2026-05-12 19:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjectionSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cliente', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('pozo', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MOTOR', 'Motor'), ('CAMARA', 'Cámara de Empuje'), ('BOMBA', 'Bomba'), ('VSD', 'Variador / VSD'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serial', models.CharField(max_length=100)),
                ('parte_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_reparacion', models.DateField(blank=True, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('fecha_desinstalacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='runlife.injectionsystem')),
            ],
            options={
                'ordering': ['sistema', 'tipo', '-activo'],
            },
        ),
        migrations.CreateModel(
            name='ComponentChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MOTOR', 'Motor'), ('CAMARA', 'Cámara de Empuje'), ('BOMBA', 'Bomba'), ('VSD', 'Variador / VSD'), ('OTRO', 'Otro')], max_length=20)),
                ('fecha_cambio', models.DateField(default=django.utils.timezone.localdate)),
                ('runlife_anterior_dias', models.PositiveIntegerField(default=0)),
                ('motivo_cambio', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_cambios', to='runlife.injectionsystem')),
                ('componente_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_como_anterior', to='runlife.systemcomponent')),
                ('componente_nuevo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_como_nuevo', to='runlife.systemcomponent')),
            ],
            options={
                'ordering': ['-fecha_cambio', '-creado_en'],
            },
        ),
    ]
