# Generated by Django 6.0.4 on 2026-05-12 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='componentchangelog',
            options={'ordering': ['-fecha_cambio', '-creado_en'], 'verbose_name': 'Historial de Cambio', 'verbose_name_plural': 'Historial de Cambios'},
        ),
        migrations.AlterModelOptions(
            name='injectionsystem',
            options={'ordering': ['campo__cliente__nombre', 'campo__nombre', 'nombre'], 'verbose_name': 'Sistema de Inyección', 'verbose_name_plural': 'Sistemas de Inyección'},
        ),
        migrations.AlterModelOptions(
            name='systemcomponent',
            options={'ordering': ['sistema', 'tipo', '-activo', 'serial'], 'verbose_name': 'Componente del Sistema', 'verbose_name_plural': 'Componentes del Sistema'},
        ),
        migrations.RemoveField(
            model_name='injectionsystem',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='injectionsystem',
            name='ubicacion',
        ),
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='clientes_runlife', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente RunLife',
                'verbose_name_plural': 'Clientes RunLife',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FieldLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='runlife.clientaccount')),
            ],
            options={
                'verbose_name': 'Campo / Locación',
                'verbose_name_plural': 'Campos / Locaciones',
                'ordering': ['cliente__nombre', 'nombre'],
                'unique_together': {('cliente', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='injectionsystem',
            name='campo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sistemas', to='runlife.fieldlocation'),
            preserve_default=False,
        ),
    ]
