# Generated by Django 6.0.4 on 2026-05-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0003_fieldlocation_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MOTOR', 'Motor'), ('CAMARA', 'Cámara de Empuje'), ('BOMBA', 'Bomba'), ('COOLER', 'Cooler'), ('VSD', 'Variador')], max_length=20)),
                ('horas_mantenimiento', models.IntegerField(help_text='Cada cuántas horas se hace mantenimiento')),
                ('dias_mantenimiento', models.IntegerField(blank=True, help_text='Alternativa por días (ej: 90 días)', null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
