# Generated by Django 6.0.4 on 2026-05-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0004_maintenancerule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerule',
            options={'ordering': ['tipo', 'horas_mantenimiento'], 'verbose_name': 'Regla de Mantenimiento', 'verbose_name_plural': 'Reglas de Mantenimiento'},
        ),
        migrations.AddField(
            model_name='maintenancerule',
            name='alerta_porcentaje',
            field=models.PositiveIntegerField(default=80, help_text='Porcentaje para marcar próximo mantenimiento. Ej: 80'),
        ),
        migrations.AlterField(
            model_name='componentchangelog',
            name='tipo',
            field=models.CharField(choices=[('MOTOR', 'Motor'), ('CAMARA', 'Cámara de Empuje'), ('BOMBA', 'Bomba'), ('COOLER', 'Cooler'), ('VSD', 'Variador / VSD'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerule',
            name='dias_mantenimiento',
            field=models.PositiveIntegerField(blank=True, help_text='Alternativa por días. Si se deja vacío, se calcula con horas / 24.', null=True),
        ),
        migrations.AlterField(
            model_name='maintenancerule',
            name='horas_mantenimiento',
            field=models.PositiveIntegerField(help_text='Cada cuántas horas se debe realizar mantenimiento'),
        ),
        migrations.AlterField(
            model_name='maintenancerule',
            name='tipo',
            field=models.CharField(choices=[('MOTOR', 'Motor'), ('CAMARA', 'Cámara de Empuje'), ('BOMBA', 'Bomba'), ('COOLER', 'Cooler'), ('VSD', 'Variador / VSD'), ('OTRO', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='systemcomponent',
            name='tipo',
            field=models.CharField(choices=[('MOTOR', 'Motor'), ('CAMARA', 'Cámara de Empuje'), ('BOMBA', 'Bomba'), ('COOLER', 'Cooler'), ('VSD', 'Variador / VSD'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
