# Generated by Django 6.0.4 on 2026-05-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0005_alter_maintenancerule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerule',
            name='campo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_mantenimiento', to='runlife.fieldlocation'),
        ),
        migrations.AddField(
            model_name='maintenancerule',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas_mantenimiento', to='runlife.clientaccount'),
        ),
    ]
