# Generated by Django 6.0.4 on 2026-05-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0006_maintenancerule_campo_maintenancerule_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcomponent',
            name='fecha_proximo_mantenimiento_programado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemcomponent',
            name='fecha_ultimo_mantenimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
