# Generated by Django 6.0.4 on 2026-05-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0007_systemcomponent_fecha_proximo_mantenimiento_programado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemcomponent',
            name='fecha_proximo_mantenimiento_programado',
        ),
    ]
