# Generated by Django 6.0.4 on 2026-05-15 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0008_remove_systemcomponent_fecha_proximo_mantenimiento_programado'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectionsystem',
            name='fecha_instalacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
