# Generated by Django 6.0.4 on 2026-05-20 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0009_injectionsystem_fecha_instalacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('frecuencia', models.FloatField(blank=True, null=True)),
                ('corriente_motor', models.FloatField(blank=True, null=True)),
                ('voltaje_motor', models.FloatField(blank=True, null=True)),
                ('kw', models.FloatField(blank=True, null=True)),
                ('presion_succion', models.FloatField(blank=True, null=True)),
                ('presion_descarga', models.FloatField(blank=True, null=True)),
                ('caudal', models.FloatField(blank=True, null=True)),
                ('vibracion_camara', models.FloatField(blank=True, null=True)),
                ('temperatura_camara', models.FloatField(blank=True, null=True)),
                ('vibracion_bomba1', models.FloatField(blank=True, null=True)),
                ('vibracion_bomba2', models.FloatField(blank=True, null=True)),
                ('vibracion_bomba3', models.FloatField(blank=True, null=True)),
                ('vibracion_bomba4', models.FloatField(blank=True, null=True)),
                ('bomba3_aplica', models.BooleanField(default=True)),
                ('bomba4_aplica', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoreos', to='runlife.injectionsystem')),
            ],
        ),
    ]
