# Generated by Django 6.0.4 on 2026-05-20 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0010_operationalmonitoring'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalmonitoring',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Monitoreo Operacional', 'verbose_name_plural': 'Monitoreos Operacionales'},
        ),
        migrations.CreateModel(
            name='OperationalLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Límites estándar', max_length=120)),
                ('vib_alerta', models.FloatField(default=4.5)),
                ('vib_critico', models.FloatField(default=7.0)),
                ('temp_alerta', models.FloatField(default=75.0)),
                ('temp_critico', models.FloatField(default=90.0)),
                ('dp_alerta', models.FloatField(default=300.0)),
                ('dp_critico', models.FloatField(default=0.0)),
                ('activo', models.BooleanField(default=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limites_operativos', to='runlife.fieldlocation')),
            ],
            options={
                'verbose_name': 'Límite Operativo',
                'verbose_name_plural': 'Límites Operativos',
            },
        ),
    ]
