# Generated by Django 6.0.4 on 2026-05-20 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0011_alter_operationalmonitoring_options_operationallimit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationallimit',
            options={},
        ),
        migrations.AddField(
            model_name='operationallimit',
            name='caudal_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationallimit',
            name='caudal_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationallimit',
            name='presion_descarga_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationallimit',
            name='presion_descarga_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationallimit',
            name='presion_succion_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationallimit',
            name='presion_succion_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationallimit',
            name='sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limites_operativos', to='runlife.injectionsystem'),
        ),
    ]
