# Generated by Django 6.0.4 on 2026-05-22 12:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0012_alter_operationallimit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationalmonitoring',
            options={'ordering': ['-fecha', '-hora']},
        ),
        migrations.AddField(
            model_name='systemcomponent',
            name='dias_garantia',
            field=models.PositiveIntegerField(default=365, help_text='Días de garantía aplicables al componente.'),
        ),
        migrations.AddField(
            model_name='systemcomponent',
            name='fabricado_por_nosotros',
            field=models.BooleanField(default=False, help_text='Marcar si el componente fue fabricado por IMPETUS / Oil & Gas.'),
        ),
        migrations.AddField(
            model_name='systemcomponent',
            name='fecha_garantia_inicio',
            field=models.DateField(blank=True, help_text='Fecha desde la cual inicia la garantía. Si se deja vacío, usa instalación o reparación.', null=True),
        ),
        migrations.AddField(
            model_name='systemcomponent',
            name='reparado_por_nosotros',
            field=models.BooleanField(default=False, help_text='Marcar si el componente fue reparado por IMPETUS / Oil & Gas.'),
        ),
        migrations.AlterField(
            model_name='operationalmonitoring',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='operationalmonitoring',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
