# Generated by Django 6.0.4 on 2026-05-22 14:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0013_alter_operationalmonitoring_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemcomponent',
            name='fabricado_por_nosotros',
        ),
        migrations.RemoveField(
            model_name='systemcomponent',
            name='fecha_garantia_inicio',
        ),
        migrations.RemoveField(
            model_name='systemcomponent',
            name='reparado_por_nosotros',
        ),
        migrations.AddField(
            model_name='systemcomponent',
            name='fecha_entrega_cliente',
            field=models.DateField(blank=True, help_text='Fecha de entrega al cliente. Desde esta fecha inicia la garantía IMPETUS.', null=True),
        ),
        migrations.AddField(
            model_name='systemcomponent',
            name='origen',
            field=models.CharField(choices=[('IMPETUS_FAB', 'Fabricado por IMPETUS'), ('IMPETUS_REP', 'Reparado por IMPETUS'), ('CLIENTE', 'Equipo del cliente')], default='CLIENTE', help_text='Indica si el componente fue fabricado o reparado por IMPETUS, o si pertenece al cliente.', max_length=20),
        ),
        migrations.AlterField(
            model_name='systemcomponent',
            name='sistema',
            field=models.ForeignKey(blank=True, help_text='Sistema donde está instalado. Puede quedar vacío cuando el componente está en bodega del campo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='runlife.injectionsystem'),
        ),
        migrations.CreateModel(
            name='BodegaCampoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega_cliente', models.DateField(default=django.utils.timezone.localdate, help_text='Fecha en que el componente reparado/fabricado fue entregado al cliente.')),
                ('fecha_ingreso_bodega', models.DateField(default=django.utils.timezone.localdate)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodega_items', to='runlife.fieldlocation')),
                ('componente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bodega_item', to='runlife.systemcomponent')),
                ('sistema_instalado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='componentes_desde_bodega', to='runlife.injectionsystem')),
            ],
            options={
                'verbose_name': 'Bodega de Campo',
                'verbose_name_plural': 'Bodega de Campo',
                'ordering': ['campo__cliente__nombre', 'campo__nombre', '-disponible', 'componente__serial'],
            },
        ),
    ]
