# Generated by Django 6.0.4 on 2026-05-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0014_remove_systemcomponent_fabricado_por_nosotros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerule',
            name='sistemas',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los sistemas a los que aplica esta regla. Si se deja vacío, aplica a todo el campo o cliente.', related_name='reglas_mantenimiento_sistemas', to='runlife.injectionsystem'),
        ),
        migrations.AddField(
            model_name='operationallimit',
            name='sistemas',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los sistemas a los que aplica este límite. Si se deja vacío, aplica a todo el campo.', related_name='limites_operativos_masivos', to='runlife.injectionsystem'),
        ),
    ]
