# Generated by Django 6.0.4 on 2026-05-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runlife', '0015_maintenancerule_sistemas_operationallimit_sistemas'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentchangelog',
            name='causa_falla',
            field=models.TextField(blank=True, help_text='Causa o modo de falla identificado.', null=True),
        ),
        migrations.AddField(
            model_name='componentchangelog',
            name='es_falla',
            field=models.BooleanField(default=False, help_text='Marcar cuando el reemplazo fue consecuencia de una falla. Alimenta MTBF.'),
        ),
        migrations.AddField(
            model_name='componentchangelog',
            name='motivo_tipo',
            field=models.CharField(choices=[('FALLA', 'Falla'), ('PREVENTIVO', 'Mantenimiento preventivo'), ('UPGRADE', 'Mejora / Upgrade'), ('ROTACION', 'Rotación'), ('GARANTIA', 'Garantía'), ('OTRO', 'Otro')], default='OTRO', help_text='Clasificación del cambio para análisis de mantenimiento y MTBF.', max_length=20),
        ),
        migrations.AddField(
            model_name='componentchangelog',
            name='posicion_bomba',
            field=models.CharField(blank=True, choices=[('LOWER', 'Lower'), ('MIDDLE', 'Middle'), ('UPPER', 'Upper'), ('GENERAL', 'General')], help_text='Aplica cuando el componente reemplazado es una bomba: lower, middle, upper o general.', max_length=20, null=True),
        ),
    ]
